In [11]:
# import tensorflow as tf
# from keras.callbacks import ModelCheckpoint, LambdaCallback
# from keras.callbacks import EarlyStopping, TensorBoard
# import argparse
# import midi
# import os

# from constants import *
from dataset import *
# from generate import *
from midi_util import midi_encode, midi_decode
# from model import *

In [97]:
# import argparse

# parser = argparse.ArgumentParser(description='Process some integers.')
# parser.add_argument('integers', metavar='N', type=int, nargs='+',
#                     help='an integer for the accumulator')
# parser.add_argument('--sum', dest='accumulate', action='store_const',
#                     const=sum, default=max,
#                     help='sum the integers (default: find the max)')

# args = parser.parse_args()
# print(args.accumulate(args.integers))

In [2]:
np.minimum(np.stack([[[1,1,2,], [2,0.1,1]],[[1,1,2,], [2,3,1]]], axis=2), 1)

array([[[1. , 1. ],
        [1. , 1. ],
        [1. , 1. ]],

       [[1. , 1. ],
        [0.1, 1. ],
        [1. , 1. ]]])

In [27]:
styles = [
       [
        'data/3T',
    ],
]

In [28]:
np.ceil([[1,1,2,], [2,3,1]])

array([[1., 1., 2.],
       [2., 3., 1.]])

In [45]:
SEQ_LEN

128

In [90]:
BATCH_SIZE

16

In [83]:
train_data, train_labels = load_all(styles, BATCH_SIZE, SEQ_LEN)

In [95]:
len(train_data)

4

In [84]:
train_data[0].shape

(124, 128, 48, 3)

In [94]:
train_data[2].shape

(124, 128, 16)

In [86]:
train_labels[0].shape

(124, 128, 48, 3)

In [63]:
train_data[0].shape

(124, 128, 48, 3)

In [91]:
BATCH_SIZE, NOTES_PER_BAR

(16, 16)

In [5]:
SEQ_LEN

128

In [70]:
for i in list(range(0, 15, 5)):
    print(np.arange(15)[i:i+3])
    print(np.arange(15)[i+1:i+3+1])
    

[0 1 2]
[1 2 3]
[5 6 7]
[6 7 8]
[10 11 12]
[11 12 13]


In [15]:
pattern = midi.read_midifile('data/3T/I_Need_You.mid')

In [4]:
train_data, train_labels

([array([], dtype=float64),
  array([], dtype=float64),
  array([], dtype=float64),
  array([], dtype=float64)],
 [array([], dtype=float64)])

In [7]:
midi.

<module 'midi' from '/anaconda3/lib/python3.6/site-packages/midi/__init__.py'>

In [17]:
a = midi_decode(pattern)

In [18]:
a.shape

(1976, 128, 3)

In [43]:
b = clamp_midi(a)
b.shape

(1976, 48, 3)

In [49]:
c = stagger(b, SEQ_LEN)
len(c)

2

In [51]:
np.array(c[0]).shape

(124, 128, 48, 3)

In [52]:
np.array(c[1]).shape

(124, 128, 48, 3)

In [80]:
(np.array(c[0][1]) == np.array(c[1][0])).any()

True

In [81]:
SEQ_LEN

128

In [82]:
NOTES_PER_BAR

16